CREATE TABLE IF NOT EXISTS error404labs.date_notes (
    id SERIAL PRIMARY KEY,
    note_date DATE NOT NULL UNIQUE,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
